// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWQIJd0Y8Ham6wZfXFoPM5R8V1U6F8-os',
    appId: '1:77344710712:web:2e0faf6e2f70809416c6cd',
    messagingSenderId: '77344710712',
    projectId: 'movie-app-2d417',
    authDomain: 'movie-app-2d417.firebaseapp.com',
    storageBucket: 'movie-app-2d417.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQZNG048esq52ilZaHRG30P1_PzdEdSYI',
    appId: '1:77344710712:android:3e97ff1ec07384f516c6cd',
    messagingSenderId: '77344710712',
    projectId: 'movie-app-2d417',
    storageBucket: 'movie-app-2d417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxrh2Txnq-zlnUOacx3K76HfqisbCGfI',
    appId: '1:77344710712:ios:006e712a27e7511416c6cd',
    messagingSenderId: '77344710712',
    projectId: 'movie-app-2d417',
    storageBucket: 'movie-app-2d417.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );
}
